//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Polizovateli
    {
        public int KodPolizovatieli { get; set; }
        [Required(ErrorMessage = "Поле Логин не должно быть пустым")]
        public string LoginPolizovateli { get; set; }
        public string ParoliPolizovateli { get; set; }
    
        public virtual DanniePersonal DanniePersonal { get; set; }
    }
}
