//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zanitie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zanitie()
        {
            this.InfoZanitia = new HashSet<InfoZanitia>();
            this.Kolichistvo = new HashSet<Kolichistvo>();
        }
    
        public int KodZanitia { get; set; }
        public string NazvanieZanitia { get; set; }
        public string OpisanieZanitia { get; set; }
        public int TipZanitia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoZanitia> InfoZanitia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolichistvo> Kolichistvo { get; set; }
        public virtual Tipzanitia Tipzanitia1 { get; set; }
    }
}
