//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoZanitia
    {
        public int KodZanitia { get; set; }
        public int Zanitia { get; set; }
        public System.TimeSpan VremiZanitia { get; set; }
        public int Trener { get; set; }
        public Nullable<System.DateTime> DataZanitia { get; set; }
    
        public virtual DanniePersonal DanniePersonal { get; set; }
        public virtual Zanitie Zanitie { get; set; }
    }
}
