//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        public int KodOplati { get; set; }
        public int Client { get; set; }
        public int Aboniment { get; set; }
        public Nullable<System.DateTime> DataOplati { get; set; }
        public Nullable<int> Summa { get; set; }
        public int SposobOplati { get; set; }
    
        public virtual Aboniment Aboniment1 { get; set; }
        public virtual SposobOplati SposobOplati1 { get; set; }
    }
}
